name: Run tg_sender daily

on:
  schedule:
    - cron: "0 18 * * *"  # каждый день в 21:00 по МСК

jobs:
  run_python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tg_sender script
        run: python tg_sender

